// Single data-access abstraction. Reads real data generated by
// scripts/build-data.ts from data/generated/ when present, falling back to
// hand-written fixtures for anything the pipeline doesn't produce yet
// (position-group grades, QB deep dive, depth chart, opponent matchup
// detail, injuries, news — these need the ESPN/roster layer from Phase 2).
// In production this will read from Vercel Blob instead of local disk; that
// swap only touches this file, never the pages/components that call it.

import { readFile } from "node:fs/promises";
import path from "node:path";
import * as fixtures from "./fixtures";
import type {
  Game,
  GameRecap,
  InjuryReportEntry,
  NewsItem,
  OpponentMatchupData,
  PositionGroupReportCard,
  QBDeepDive,
  ScheduleRow,
  SeasonProjection,
  Team,
  TeamStatSnapshot,
  DepthChartEntry,
} from "./types";

const GENERATED_DIR = path.join(process.cwd(), "data", "generated");

async function readGenerated<T>(filename: string): Promise<T | null> {
  try {
    const content = await readFile(path.join(GENERATED_DIR, filename), "utf-8");
    return JSON.parse(content) as T;
  } catch {
    return null;
  }
}

export async function getTeam(): Promise<Team> {
  return fixtures.team;
}

export async function getLastGame(): Promise<Game> {
  return (await readGenerated<Game>("last-game.json")) ?? fixtures.lastGame;
}

export async function getNextGame(): Promise<Game> {
  return (await readGenerated<Game>("next-game.json")) ?? fixtures.nextGame;
}

export async function getLastGameRecap(): Promise<GameRecap> {
  const lastGame = await getLastGame();
  return (
    (await readGenerated<GameRecap>(`recap-${lastGame.id}.json`)) ??
    fixtures.lastGameRecap
  );
}

export async function getRecapByGameId(
  gameId: string
): Promise<GameRecap | null> {
  const real = await readGenerated<GameRecap>(`recap-${gameId}.json`);
  if (real) return real;
  return fixtures.lastGameRecap.gameId === gameId ? fixtures.lastGameRecap : null;
}

export async function getAllRecaps(): Promise<
  Array<{ game: Game; recap: GameRecap }>
> {
  const index = await readGenerated<string[]>("recap-index.json");
  if (index && index.length > 0) {
    const rows = await Promise.all(
      index.map(async (gameId) => {
        const recap = await readGenerated<GameRecap>(`recap-${gameId}.json`);
        const schedule = await getSchedule();
        const scheduleRow = schedule.find((r) => r.gameId === gameId);
        const lastGame = await getLastGame();
        const game: Game =
          lastGame.id === gameId
            ? lastGame
            : {
                id: gameId,
                season: 2026,
                week: scheduleRow?.week ?? 0,
                seasonType: "REG",
                date: scheduleRow?.date ?? "",
                homeTeam: scheduleRow?.homeAway === "home" ? "NE" : scheduleRow?.opponent ?? "",
                awayTeam: scheduleRow?.homeAway === "away" ? "NE" : scheduleRow?.opponent ?? "",
                status: "final",
                venue: "",
              };
        return recap ? { game, recap } : null;
      })
    );
    const real = rows.filter((r): r is { game: Game; recap: GameRecap } => r !== null);
    if (real.length > 0) return real.reverse();
  }
  return [{ game: fixtures.lastGame, recap: fixtures.lastGameRecap }];
}

export async function getTeamStats(): Promise<TeamStatSnapshot> {
  return (await readGenerated<TeamStatSnapshot>("team-stats.json")) ?? fixtures.teamStats;
}

export async function getPositionGroupReportCards(): Promise<
  PositionGroupReportCard[]
> {
  return fixtures.positionGroupReportCards;
}

export async function getQBDeepDive(): Promise<QBDeepDive> {
  return fixtures.qbDeepDive;
}

export async function getDepthChart(): Promise<DepthChartEntry[]> {
  return fixtures.depthChart;
}

export async function getSchedule(): Promise<ScheduleRow[]> {
  return (await readGenerated<ScheduleRow[]>("schedule.json")) ?? fixtures.schedule;
}

export async function getSeasonProjection(): Promise<SeasonProjection> {
  return fixtures.projection;
}

export async function getOpponentMatchup(): Promise<OpponentMatchupData> {
  return fixtures.opponentMatchup;
}

export async function getInjuries(): Promise<InjuryReportEntry[]> {
  return fixtures.injuries;
}

export async function getNews(): Promise<NewsItem[]> {
  return fixtures.news;
}
