// Enriches the most recent recap and the upcoming opponent matchup with
// AI-written content, grounded entirely in real data already generated by
// the rest of the pipeline: real box-score stats (from build-data.ts),
// real fetched news headlines (from build-espn-data.ts), real opponent
// matchup grades (from build-next-game-data.ts). Nothing here invents
// facts — every prompt hands the model the real numbers and real article
// text and asks it to write from those, never beyond them.
//
// Run after: build-data.ts, build-next-game-data.ts, build-espn-data.ts
// (or fetch-news-sources.ts, since news.json may already be committed
// fresh from the separate headlines workflow — this script never fetches
// news itself, only reads whatever's already on disk).
//
// Fails soft throughout: if ANTHROPIC_API_KEY is missing, or any call
// fails, the existing template-based content stays in place untouched.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { generateChecked, generateJson } from "./lib/claude";
import { checkGrounding } from "./lib/aiChecks";
import { AI_VERSION } from "./lib/aiVersion";
import { recordAiOutcome } from "./lib/aiDiagnostics";
import { formatGrade, gradeWords } from "../lib/calc/ranks";
import type { Game, GameRecap, NewsItem, OpponentMatchupData, ScheduleRow } from "../lib/data/types";

const GENERATED_DIR = path.join(process.cwd(), "data", "generated");
const TEAM = "NE";

// See scripts/lib/aiVersion.ts for what each version changed.

// Rough league-wide norms, so "8 of 12 third downs allowed" can't be
// read as a good day for the defense.
const LEAGUE_NORMS =
  "League norms for context: teams convert about 40% of third downs and score touchdowns on about 55% of red-zone trips; an EPA/play of 0.00 is exactly average (positive is good for an offense, negative is good for a defense).";

// Ranks and EPA in words, so the model doesn't have to interpret the sign
// or the scale itself — that's where version 2 went wrong.
function rankWords(rank: number): string {
  if (rank <= 5) return "among the NFL's best";
  if (rank <= 12) return "above average";
  if (rank <= 20) return "around average";
  if (rank <= 27) return "below average";
  return "among the NFL's worst";
}

function epaWords(epa: number, side: "offense" | "defense"): string {
  const good = side === "offense" ? epa > 0 : epa < 0;
  const size = Math.abs(epa);
  const degree = size < 0.05 ? "about average" : size < 0.15 ? "better than average" : "much better than average";
  if (degree === "about average") return "about average";
  return good ? degree : degree.replace("better", "worse");
}

function scoringLine(team: string, s: { td: number; fg: number; safety: number }): string {
  const parts = [`${s.td} TD`, `${s.fg} FG`];
  if (s.safety > 0) parts.push(`${s.safety} safety`);
  return `${team}: ${parts.join(", ")}`;
}

const FAN_VOICE_SYSTEM = `You write for The Foxboro Beacon, an independent New England Patriots fan site. Write in the voice of an extremely smart, funny, and highly articulate die-hard Patriots fan — someone who clearly knows the sport deeply, writes with real wit and a distinct voice, and can turn a sharp line, but is never mean-spirited, never vulgar, never disrespectful of players. Accuracy comes first: use ONLY the facts given to you below — never invent stats, plays, injuries, quotes, or events that aren't explicitly provided, and never exaggerate a fact beyond what's given. Be specific whenever the facts allow it: name the actual players, teams, and numbers involved rather than describing things generically. If you're not given enough to say something specific, stay general rather than making something up.

When two numbers you're given can be read together, frame them that way instead of stating each in isolation — a rank next to the metric it's ranked in ("31st in the league"), or a number set against another one you were also given (this week's form next to last week's, our number next to the opponent's). This is about connecting facts you already have, not introducing new ones: never state a specific historical record, streak, or "since [year]" claim unless that exact fact is explicitly given to you below — if it's not there, don't invent it, and don't imply comparative context (e.g. "best since") beyond what the numbers you have actually support.

Respond with ONLY valid JSON, no markdown formatting, no code fences, no extra commentary.`;

async function readJson<T>(filename: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(path.join(GENERATED_DIR, filename), "utf-8")) as T;
  } catch {
    return null;
  }
}

function relevantNews(news: NewsItem[], centerDate: string, daysBefore: number, daysAfter: number): NewsItem[] {
  const center = new Date(`${centerDate}T12:00:00Z`).getTime();
  const dayMs = 86400000;
  return news
    .filter((n) => {
      const t = new Date(n.publishedAt).getTime();
      return t >= center - daysBefore * dayMs && t <= center + daysAfter * dayMs;
    })
    .slice(0, 10);
}

function formatArticles(items: NewsItem[]): string {
  if (items.length === 0) return "(no relevant articles found)";
  return items
    .map((n) => `- [${n.type}] ${n.headline}: ${n.summary}`)
    .join("\n");
}

async function buildRecapContent() {
  // Every archived game whose AI content is missing or was written under
  // an older prompt — not only the most recent one, or a wrong recap from
  // an earlier week would stay wrong forever.
  const index = (await readJson<string[]>("recap-index.json")) ?? [];
  const schedule = (await readJson<ScheduleRow[]>("schedule.json")) ?? [];
  const news = (await readJson<NewsItem[]>("news.json")) ?? [];

  for (const gameId of index) {
    const recap = await readJson<GameRecap>(`recap-${gameId}.json`);
    const row = schedule.find((r) => r.gameId === gameId);
    if (!recap || !row || row.ourScore === undefined || row.theirScore === undefined) continue;
    if (recap.fanTake && (recap.aiVersion ?? 1) >= AI_VERSION) continue;

    const isHome = row.homeAway === "home";
    const opponent = row.opponent;
    const usScore = row.ourScore;
    const themScore = row.theirScore;
    const articles = relevantNews(news, row.date, 1, 5);
    const star = recap.playerOfTheGame;

    const weekday = new Date(`${row.date}T12:00:00Z`).toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      timeZone: "UTC",
    });
    const user = `Date: ${weekday} (${row.date}). Don't describe the time of day — it isn't given.
Final score: New England ${usScore}, ${opponent} ${themScore} (${usScore > themScore ? "Patriots win" : usScore === themScore ? "tie" : "Patriots loss"}).
Location: ${isHome ? `a home game for New England, at ${row.venue || "Gillette Stadium"} in Foxborough` : `a road game — New England played at ${opponent}${row.venue ? `, ${row.venue}` : ""}. It was NOT in Foxborough`}.
How the points were scored — ${recap.scoring ? `${scoringLine("New England", recap.scoring.us)}; ${scoringLine(opponent, recap.scoring.them)}` : "not available, so don't describe it"}.
Real computed stats: offensive EPA/play ${recap.epaPerPlay.offense.toFixed(2)} (${epaWords(recap.epaPerPlay.offense, "offense")}), defensive EPA/play allowed ${recap.epaPerPlay.defense.toFixed(2)} (${epaWords(recap.epaPerPlay.defense, "defense")} — for a defense, negative is good), turnover margin ${recap.turnoverMargin}, red zone offense ${recap.redZone.offense.td} TDs on ${recap.redZone.offense.att} trips, red zone defense allowed ${recap.redZone.defense.td} TDs on ${recap.redZone.defense.att} trips, third down offense ${recap.thirdDown.offense.conv}/${recap.thirdDown.offense.att}, third downs allowed ${recap.thirdDown.defense.conv}/${recap.thirdDown.defense.att}.
${LEAGUE_NORMS}
New England's player of the game (by win probability added, among New England players only — no opponent players were measured, so don't compare him to them): ${star.playerName}, ${(star.wpa * 100).toFixed(0)}% WPA. Refer to players by the full names given here or in the articles, never a guessed first name.

Real articles about this game:
${formatArticles(articles)}

Respond with ONLY this JSON shape:
{"fanTake": "3-5 sentences in the fan voice describing what happened and how it feels", "good": ["1-2 short bullet points, each one sentence"], "bad": ["1-2 short bullet points"], "ugly": ["0-2 short bullet points, omit if nothing rises to 'ugly'"]}`;

    type RecapAi = { fanTake: string; good: string[]; bad: string[]; ugly: string[] };
    // 1,000 tokens: a take plus up to six bullets for a lopsided game
    // can run past 500, and a reply cut off mid-JSON can't be parsed.
    const { result, outcome } = await generateChecked<RecapAi>(
      (prompt) => generateJson<RecapAi>(FAN_VOICE_SYSTEM, prompt, 1000),
      user,
      (r) => [r.fanTake, ...(r.good ?? []), ...(r.bad ?? []), ...(r.ugly ?? [])].join(" "),
      (text) => checkGrounding(text, { facts: user, isHome, playerNames: [star.playerName] }),
      `Recap ${gameId}`
    );
    await recordAiOutcome(`recap ${gameId}`, outcome);

    if (!result?.fanTake) {
      console.log(`Recap AI content for ${gameId} not written — the plain computed recap stays.`);
      continue;
    }

    recap.fanTake = result.fanTake;
    if (result.good?.length) recap.goodBadUgly.good = result.good;
    if (result.bad?.length) recap.goodBadUgly.bad = result.bad;
    recap.goodBadUgly.ugly = result.ugly ?? [];
    recap.aiVersion = AI_VERSION;

    await writeFile(path.join(GENERATED_DIR, `recap-${gameId}.json`), JSON.stringify(recap, null, 2));
    console.log(`Wrote AI-generated fanTake + goodBadUgly for ${gameId}`);
  }
}

async function buildPreviewContent() {
  const nextGame = await readJson<Game>("next-game.json");
  const matchup = await readJson<OpponentMatchupData>("opponent-matchup.json");
  if (!nextGame || !matchup) {
    console.log("next-game.json or opponent-matchup.json not found — skipping preview AI content.");
    return;
  }

  const news = (await readJson<NewsItem[]>("news.json")) ?? [];
  const isHome = nextGame.homeTeam === TEAM;
  const articles = relevantNews(news, nextGame.date, 6, 0);

  // Counted here rather than left to the model, which read five meetings
  // (2-3) as "2-3 over the last two years".
  const h2hWins = matchup.headToHead.filter((h) => h.result === "W").length;
  const h2hLosses = matchup.headToHead.filter((h) => h.result === "L").length;
  const formGames = (side: { gamesPlayed: number }) => Math.min(3, side.gamesPlayed);

  const user = `Upcoming game: New England ${isHome ? `hosts ${matchup.opponent} at ${nextGame.venue || "Gillette Stadium"} in Foxborough` : `plays at ${matchup.opponent}, ${nextGame.venue || "on the road"} — a road game, NOT in Foxborough`}, Week ${nextGame.week}, ${nextGame.date}.
${matchup.opponent}'s league ranks by EPA/play (1 = best of 32): offense ${matchup.opponentEpaRank.offense} of 32 (${rankWords(matchup.opponentEpaRank.offense)}), defense ${matchup.opponentEpaRank.defense} of 32 (${rankWords(matchup.opponentEpaRank.defense)}).
Unit grades — IMPORTANT: these are 0-100 scores where 100 is the best in the NFL and 0 the worst. They are NOT ranks; a grade of 6 means near the bottom of the league.
${matchup.positionGroupMatchups.map((m) => { const [ours, theirs] = m.group.toLowerCase().split(" vs. "); return `- New England's ${ours} ${formatGrade(m.ourGrade)} (${gradeWords(m.ourGrade)}) vs. ${matchup.opponent}'s ${theirs} ${formatGrade(m.theirGrade)} (${gradeWords(m.theirGrade)})`; }).join("\n")}
Matchup of the week: ${matchup.matchupOfTheWeek.title} — ${matchup.matchupOfTheWeek.description}
Recent form (net EPA/play, positive is good): New England ${matchup.recentForm.us.last3EpaPerPlay.toFixed(2)} over its last ${formGames(matchup.recentForm.us)} games, ${matchup.opponent} ${matchup.recentForm.them.last3EpaPerPlay.toFixed(2)} over its last ${formGames(matchup.recentForm.them)}.
Head-to-head, last ${matchup.headToHead.length} meetings (New England ${h2hWins}-${h2hLosses} in them): ${matchup.headToHead.map((h) => `${h.season}: ${h.result} ${h.score}`).join(", ") || "none on record"}
${matchup.bettingContext ? `Betting line: New England ${matchup.bettingContext.spread > 0 ? "+" : ""}${matchup.bettingContext.spread}, O/U ${matchup.bettingContext.overUnder}` : ""}
Opponent injuries: ${matchup.opponentInjuries.map((i) => `${i.playerName} (${i.position}) — ${i.injury}, ${i.gameStatus ?? "status unclear"}`).join("; ") || "none reported yet this week"}

Real articles about this upcoming game:
${formatArticles(articles)}

Respond with ONLY this JSON shape:
{"previewTake": "3-5 sentences in the fan voice previewing this matchup — what you're excited or nervous about, grounded only in the facts above"}`;

  const { result, outcome } = await generateChecked<{ previewTake: string }>(
    (prompt) => generateJson<{ previewTake: string }>(FAN_VOICE_SYSTEM, prompt, 800),
    user,
    (r) => r.previewTake ?? "",
    (text) => checkGrounding(text, { facts: user, isHome }),
    "Preview"
  );
  await recordAiOutcome(`preview ${nextGame.id}`, outcome);
  if (!result?.previewTake) {
    console.log("Preview AI content not written — the page shows no preview this run.");
    return;
  }

  matchup.previewTake = result.previewTake;
  await writeFile(
    path.join(GENERATED_DIR, "opponent-matchup.json"),
    JSON.stringify(matchup, null, 2)
  );
  console.log(`Wrote AI-generated previewTake for ${nextGame.id}`);
}

async function main() {
  await buildRecapContent();
  await buildPreviewContent();
}

main().catch((err) => {
  console.error(err);
  // Never fail the build over AI content — log and exit clean.
  process.exit(0);
});
