// Enriches the most recent recap and the upcoming opponent matchup with
// AI-written content, grounded entirely in real data already generated by
// the rest of the pipeline: real box-score stats (from build-data.ts),
// real fetched news headlines (from build-espn-data.ts), real opponent
// matchup grades (from build-next-game-data.ts). Nothing here invents
// facts — every prompt hands the model the real numbers and real article
// text and asks it to write from those, never beyond them.
//
// Run after: build-data.ts, build-next-game-data.ts, build-espn-data.ts
// (or fetch-news-sources.ts, since news.json may already be committed
// fresh from the separate headlines workflow — this script never fetches
// news itself, only reads whatever's already on disk).
//
// Fails soft throughout: if ANTHROPIC_API_KEY is missing, or any call
// fails, the existing template-based content stays in place untouched.

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { generateJson } from "./lib/claude";
import type { Game, GameRecap, NewsItem, OpponentMatchupData } from "../lib/data/types";

const GENERATED_DIR = path.join(process.cwd(), "data", "generated");
const TEAM = "NE";

const FAN_VOICE_SYSTEM = `You write for The Foxboro Beacon, an independent New England Patriots fan site. Write in the voice of an extremely smart, funny, and highly articulate die-hard Patriots fan — someone who clearly knows the sport deeply, writes with real wit and a distinct voice, and can turn a sharp line, but is never mean-spirited, never vulgar, never disrespectful of players. Accuracy comes first: use ONLY the facts given to you below — never invent stats, plays, injuries, quotes, or events that aren't explicitly provided, and never exaggerate a fact beyond what's given. Be specific whenever the facts allow it: name the actual players, teams, and numbers involved rather than describing things generically. If you're not given enough to say something specific, stay general rather than making something up. Respond with ONLY valid JSON, no markdown formatting, no code fences, no extra commentary.`;

async function readJson<T>(filename: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(path.join(GENERATED_DIR, filename), "utf-8")) as T;
  } catch {
    return null;
  }
}

function relevantNews(news: NewsItem[], centerDate: string, daysBefore: number, daysAfter: number): NewsItem[] {
  const center = new Date(`${centerDate}T12:00:00Z`).getTime();
  const dayMs = 86400000;
  return news
    .filter((n) => {
      const t = new Date(n.publishedAt).getTime();
      return t >= center - daysBefore * dayMs && t <= center + daysAfter * dayMs;
    })
    .slice(0, 10);
}

function formatArticles(items: NewsItem[]): string {
  if (items.length === 0) return "(no relevant articles found)";
  return items
    .map((n) => `- [${n.type}] ${n.headline}: ${n.summary}`)
    .join("\n");
}

async function buildRecapContent() {
  const lastGame = await readJson<Game>("last-game.json");
  if (!lastGame || lastGame.status !== "final") {
    console.log("No completed game found — skipping recap AI content.");
    return;
  }

  const recap = await readJson<GameRecap>(`recap-${lastGame.id}.json`);
  if (!recap) {
    console.log(`recap-${lastGame.id}.json not found — skipping recap AI content.`);
    return;
  }
  if (recap.fanTake) {
    console.log(`fanTake already set for ${lastGame.id} — skipping (generated once per game).`);
    return;
  }

  const news = (await readJson<NewsItem[]>("news.json")) ?? [];
  const isHome = lastGame.homeTeam === TEAM;
  const opponent = isHome ? lastGame.awayTeam : lastGame.homeTeam;
  const usScore = isHome ? lastGame.homeScore : lastGame.awayScore;
  const themScore = isHome ? lastGame.awayScore : lastGame.homeScore;
  const articles = relevantNews(news, lastGame.date, 1, 5);

  const user = `Final score: New England ${usScore}, ${opponent} ${themScore} (${usScore! > themScore! ? "Patriots win" : usScore === themScore ? "tie" : "Patriots loss"}).
Real computed stats: offensive EPA/play ${recap.epaPerPlay.offense.toFixed(2)}, defensive EPA/play ${recap.epaPerPlay.defense.toFixed(2)}, turnover margin ${recap.turnoverMargin}, red zone offense ${recap.redZone.offense.td}/${recap.redZone.offense.att}, red zone defense allowed ${recap.redZone.defense.td}/${recap.redZone.defense.att}, third down offense ${recap.thirdDown.offense.conv}/${recap.thirdDown.offense.att}, third down defense allowed ${recap.thirdDown.defense.conv}/${recap.thirdDown.defense.att}.
Player of the game (by win probability added): ${recap.playerOfTheGame.playerName}, ${(recap.playerOfTheGame.wpa * 100).toFixed(0)}% WPA.

Real articles about this game:
${formatArticles(articles)}

Respond with ONLY this JSON shape:
{"fanTake": "3-5 sentences in the fan voice describing what happened and how it feels", "good": ["1-2 short bullet points, each one sentence"], "bad": ["1-2 short bullet points"], "ugly": ["0-2 short bullet points, omit if nothing rises to 'ugly'"]}`;

  const result = await generateJson<{
    fanTake: string;
    good: string[];
    bad: string[];
    ugly: string[];
  }>(FAN_VOICE_SYSTEM, user);

  if (!result?.fanTake) {
    console.log("Recap AI content generation failed — keeping existing narrative/goodBadUgly.");
    return;
  }

  recap.fanTake = result.fanTake;
  if (result.good?.length) recap.goodBadUgly.good = result.good;
  if (result.bad?.length) recap.goodBadUgly.bad = result.bad;
  recap.goodBadUgly.ugly = result.ugly ?? [];

  await writeFile(
    path.join(GENERATED_DIR, `recap-${lastGame.id}.json`),
    JSON.stringify(recap, null, 2)
  );
  console.log(`Wrote AI-generated fanTake + goodBadUgly for ${lastGame.id}`);
}

async function buildPreviewContent() {
  const nextGame = await readJson<Game>("next-game.json");
  const matchup = await readJson<OpponentMatchupData>("opponent-matchup.json");
  if (!nextGame || !matchup) {
    console.log("next-game.json or opponent-matchup.json not found — skipping preview AI content.");
    return;
  }

  const news = (await readJson<NewsItem[]>("news.json")) ?? [];
  const isHome = nextGame.homeTeam === TEAM;
  const articles = relevantNews(news, nextGame.date, 6, 0);

  const user = `Upcoming game: New England ${isHome ? "hosts" : "at"} ${matchup.opponent}, Week ${nextGame.week}, ${nextGame.date}.
Opponent EPA ranks: offense #${matchup.opponentEpaRank.offense} in NFL, defense #${matchup.opponentEpaRank.defense} in NFL.
Matchup of the week: ${matchup.matchupOfTheWeek.title} — ${matchup.matchupOfTheWeek.description}
Opponent recent form (net EPA/play, last 3 games): ${matchup.recentForm.last3EpaPerPlay.toFixed(2)}
Head-to-head, most recent meetings: ${matchup.headToHead.map((h) => `${h.season}: ${h.result} ${h.score}`).join(", ") || "none on record"}
${matchup.bettingContext ? `Betting line: New England ${matchup.bettingContext.spread > 0 ? "+" : ""}${matchup.bettingContext.spread}, O/U ${matchup.bettingContext.overUnder}` : ""}
Opponent injuries: ${matchup.opponentInjuries.map((i) => `${i.playerName} (${i.position}) — ${i.injury}, ${i.gameStatus ?? "status unclear"}`).join("; ") || "none reported"}

Real articles about this upcoming game:
${formatArticles(articles)}

Respond with ONLY this JSON shape:
{"previewTake": "3-5 sentences in the fan voice previewing this matchup — what you're excited or nervous about, grounded only in the facts above"}`;

  const result = await generateJson<{ previewTake: string }>(FAN_VOICE_SYSTEM, user);
  if (!result?.previewTake) {
    console.log("Preview AI content generation failed — leaving previewTake unset.");
    return;
  }

  matchup.previewTake = result.previewTake;
  await writeFile(
    path.join(GENERATED_DIR, "opponent-matchup.json"),
    JSON.stringify(matchup, null, 2)
  );
  console.log(`Wrote AI-generated previewTake for ${nextGame.id}`);
}

async function main() {
  await buildRecapContent();
  await buildPreviewContent();
}

main().catch((err) => {
  console.error(err);
  // Never fail the build over AI content — log and exit clean.
  process.exit(0);
});
